[#11] add delete on notice api
kiworkshop/community pull request #17
Opened 2019-07-31 15:31 UTC by jjj0611

- add DeleteMapping "/notices/{id}" on NoticeController#delete
- add NoticeService#deleteById
- add throw NoticeNotFoundException when invalid id input on NoticeService#deleteById
- check style test
- jacoco test coverage

##### Checklist

- [x] passing all unit and integration tests
- [x] test coverage is above 95%
- [x] no warnings from `checkstyle`
- [x] documentation is changed or added

### Description of change

- add DeleteMapping on NoticeController#delete
- add NoticeService#deleteById
- add throw NoticeNotFoundException when invaild id input on NoticeService#deleteById

2019-08-01 00:41 UTC, hrzon requested changes

2019-08-01 00:41 UTC, hrzon commented on mother-api/src/integrationTest/java/community/mother/notice/api/NoticeControllerIntTest.java
> +        .andExpect(jsonPath("$").doesNotExist());
response body가 없는 것까지 확인하셨네요 👏

2019-08-01 00:41 UTC, hrzon commented on mother-api/src/integrationTest/java/community/mother/notice/api/NoticeControllerIntTest.java
> +    //    .andExpect(status().isNotFound());
이 주석은 지워도 될 것 같습니다.

마틴 파울러는 책 <리팩토링>에서 주석은 최대한 코드로 풀어쓰라고 하더라구요. 주석은 거짓말을 할 수 있지만 코드는 거짓말을 하지 못한다고.. 주석을 코드로 풀어쓰는 여러가지 방법은 위 책에 나와있습니다~~

2019-08-01 00:41 UTC, hrzon commented on mother-api/src/main/java/community/mother/notice/exception/NoticeNotFoundException.java
> +public class NoticeNotFoundException extends RuntimeException {
upstream을 pull받으시면 제가 작성해놓은 NoticeNotFoundException을 보실수있을거에요~~ 그걸 같이 써주시면 좋을것같습니다.

2019-08-01 00:41 UTC, hrzon commented on mother-api/src/test/java/community/mother/notice/domain/NoticeRepositoryTest.java
> +  }
이 테스트는 noticeRepository.findById가 제대로 작동하는지 테스트하고 있는데, findById는 저희가 작성한 메서드가 아니니까 테스트하지 않아도 될 것 같습니다. 만약에 repository에 새로운 query method를 작성했다면 그 method가 잘 작동하는지 확인하는 테스트는 작성하면 좋습니다.

위에 제가 작성해놨던 테스트도 사실 없어도 되는 테스트입니다...😱

2019-08-01 00:41 UTC, hrzon commented on mother-api/src/test/java/community/mother/notice/service/NoticeServiceTest.java
> +    given(noticeRepository.findById(any(Long.class))).willReturn(Optional.ofNullable(noticeToDelete));
ofNullable대신 of를 쓰는건 어떨까요? getNoticeFixture()는 저희가 작성한 메서드이고, null이 아니라는게 확실하니... Optional.of를 쓰면 아래 assert문을 안 써도 됩니다.

2019-08-01 00:42 UTC, myeongjae-kim commented on mother-api/src/integrationTest/java/community/mother/notice/api/NoticeControllerIntTest.java
> +        .andExpect(jsonPath("$").doesNotExist());
헉ㅋㅋㅋ 다른계정으로 리뷰해버렸읍니다

2019-08-01 13:32 UTC, myeongjae-kim approved these changes
👏👏

2019-08-01 16:31 UTC, myangw approved these changes

2019-08-02 10:03 UTC, hrzon approved these changes

2019-08-02 10:05 UTC, merged