10 notice put
kiworkshop/community pull request #18
Opened 2019-07-31 15:56 UTC by me0768

##### Checklist

- [x] passing all unit and integration tests
- [x] test coverage is above 95%
- [x] no warnings from `checkstyle`

### Description of change

- Add NoticeController#update()
- Add NoticeService#updateNotice()
- Add Notice#updateNotice()
- Add integrationTest of NoticeController
- Add unitTests of domain, service, controller

2019-08-01 08:24 UTC, jjj0611 submitted a review, later dismissed

2019-08-01 14:08 UTC, myeongjae-kim requested changes

2019-08-01 14:08 UTC, myeongjae-kim commented on mother-api/build.gradle
> +    compileOnly 'org.projectlombok:lombok:1.18.6'
혹시 버전을 명시적으로 적은 이유가 있을까요?

버전을 생략하면 spring boot에서 알아서 적절한 버전을 선택해줍니다. https://stackoverflow.com/a/41677720

lombok의 경우 <https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/2.1.6.RELEASE> 에서 보면 1.18.8 버전이 되겠네요.

2019-08-01 14:08 UTC, myeongjae-kim commented on mother-api/src/main/java/comunity/mother/notice/domain/Notice.java
> +  public Notice updateNotice(NoticeRequestDto noticeRequestDto) {
도메인과 컨트롤러 레이어는 분리하는게 좋기 때문에, 엔티티가 Dto를 모르게 해야합니다. 엔티티와 Dto가 독립적으로 존재한다면 복잡도가 줄어듭니다.

매개변수로 NoticeRequestDto 대신에 `String title, String content`을 받으면 어떨까요~~

2019-08-01 14:08 UTC, myeongjae-kim commented on mother-api/src/main/java/comunity/mother/notice/domain/Notice.java
> +    return this;
CQRS의 관점에서 생각해보면 update method는 command입니다. Controller의 update 메서드의 리턴이 void인 것처럼 여기서도 리턴을 아무것도 안 하면 좋겠네요.

2019-08-01 14:08 UTC, myeongjae-kim commented on mother-api/src/main/java/comunity/mother/notice/service/NoticeService.java
> +    Notice savedNotice = noticeRepository.findById(id).orElseThrow(EntityNotFoundException::new);
업스트림에서 풀 받으시면 제가 작성한 NoticeNotFoundException이 있을거에요. EntityNotFoundException 대신에 NoticeNotFoundException을 사용하시면 됩니다.

2019-08-01 14:08 UTC, myeongjae-kim commented on mother-api/src/test/java/comunity/mother/notice/domain/NoticeTest.java
> +    Notice updatedNotice = savedNotice.updateNotice(noticeRequestDto);
getNoticeFixture()의 title필드와 content필드의 값이 getNoticeRequestDtoFixture()의 그것들과 똑같기 때문에 updateNotice 메서드가 아무 일 안 해도 테스트를 통과할 수 있게됩니다.

2019-08-01 14:08 UTC, myeongjae-kim commented on mother-api/src/test/java/comunity/mother/notice/service/NoticeServiceTest.java
> +    noticeService.updateNotice(1L, noticeRequestDto);
then이 하나도 없는 정말 테스트를 위한 테스트같지만.. 여기서도 테스트하는게 있긴 합니다. 불려야할 메서드들이 정말로 불리는지 확인할 수 있어요. updateNotice메서드에서 `noticeRepository.save(savedNotice.updateNotice(noticeRequestDto));`를 주석처리하고 실행해보면 `noticeRepository.save`메서드를 모킹해놓고 실행하지 않았다고 하면서 테스트가 실패합니다😀

2019-08-01 14:08 UTC, myeongjae-kim commented on mother-api/src/test/java/comunity/mother/notice/service/NoticeServiceTest.java
> +    Long updatingNoticeId = 100L;
저같은 경우는 아무 값이나 넣어도 되는 변수엔 보통 1을 넣습니다. 코드에 매직 넘버를 -1, 0, 1 이외의 숫자는 최대한 안쓰려고 하기 때문이죱... 100L대신에 1L로 하면 제 마음이 더 편해질 것 같습니다...😂

그리고 저라면 updatingNoticeId변수를 선언하지 않고 다음처럼 테스트를 작성할 것 같습니다.

```java
@Test
  void updateNotice_nonExistNotice_throwException() throws Exception {
    NoticeRequestDto noticeUpdatingRequestDto = getNoticeRequestDtoFixture();
    given(noticeRepository.findById(anyLong())).willReturn(Optional.empty());

    thenThrownBy(() -> noticeService.updateNotice(1L, noticeUpdatingRequestDto))
        .isInstanceOf(EntityNotFoundException.class);
  }
```

바로 위의 테스트에서 updateNotice메서드의 첫 번째 매개변수에 1L을 넣었으니, 여기서도 똑같이 하면 통일감을 느낄 수 있을 것 같습니다.

2019-08-01 14:14 UTC, myeongjae-kim commented on mother-api/src/main/java/comunity/mother/notice/api/NoticeController.java
> +import org.springframework.web.bind.annotation.*;
checkstyle에서 `.*`이 불-편하다고 하시네욥. IntelliJ의 Preferences -> Editor -> Code Style -> Java -> Imports -> Class count to use import with '*';와 Names count to use static import with '*';의 값을 무지막지한 값으로 변경해주시면 됩니다.

2019-08-01 14:18 UTC, me0768 commented on mother-api/build.gradle
> +    compileOnly 'org.projectlombok:lombok:1.18.6'
그 저번에 같이 환경셋팅할때 저만 안됐던거 기억하시나요 ㅜㅜㅜ
버전 안적으면 계속 안되어서 같이 푸시했습니다
최신버전은 또 명시를 해줘도 안되더라구요 ㅜ 왜그런진 아직 파악 못했어요..

2019-08-01 14:24 UTC, myeongjae-kim commented on mother-api/build.gradle
> +    compileOnly 'org.projectlombok:lombok:1.18.6'
아 맞다!! 알겠습니다 😅

2019-08-01 15:32 UTC, me0768 commented on mother-api/src/main/java/comunity/mother/notice/domain/Notice.java
> +  public Notice updateNotice(NoticeRequestDto noticeRequestDto) {
깜빡햇네용 지난번에 말씀해주셨는데 ㅜㅜ 수정햇습니다

2019-08-01 15:33 UTC, me0768 commented on mother-api/src/test/java/comunity/mother/notice/service/NoticeServiceTest.java
> +    noticeService.updateNotice(1L, noticeRequestDto);
ㅋㅋ그렇네요!

2019-08-01 15:34 UTC, me0768 commented on mother-api/src/test/java/comunity/mother/notice/service/NoticeServiceTest.java
> +    Long updatingNoticeId = 100L;
심기불편하셨군여..ㅋㅋㅋㅋㅋㅋㅋ
처음에 mocking한다는 생각 없이 1이 아닌 무언가를 넣으려고했는데, mocking이라서 상관없었어요. 앞으로는 -1 0 1 !!!

2019-08-01 15:37 UTC, me0768 commented
코드리뷰 감사합니다 !!! 모두 수정완료했습니당

2019-08-01 15:53 UTC, myeongjae-kim requested changes
늦은밤까지 고생입니다🤩 다시보니 수정할 게 좀 더 보입니다..

2019-08-01 15:53 UTC, myeongjae-kim commented on mother-api/src/test/java/community/mother/notice/api/dto/NoticeRequestDtoTest.java
> +
getNoticeUpdateRequestDtoFixture()를 새로 만드는 대신에 getNoticeRequestDto를 오버로딩해서 사용할 수 있습니다.

```java
package community.mother.notice.api.dto;

import community.common.util.MyReflectionUtils;

public class NoticeRequestDtoTest {
  public static NoticeRequestDto getNoticeRequestDtoFixture() throws Exception {
    return getNoticeRequestDtoFixture("title", "content");
  }

  public static NoticeRequestDto getNoticeRequestDtoFixture(String title, String content) throws Exception {
    NoticeRequestDto noticeRequestDto = new NoticeRequestDto();

    MyReflectionUtils.setField(noticeRequestDto, "title", title);
    MyReflectionUtils.setField(noticeRequestDto, "content", content);

    return noticeRequestDto;
  }
}
```

2019-08-01 15:53 UTC, myeongjae-kim commented on mother-api/src/integrationTest/java/community/mother/notice/api/NoticeControllerIntTest.java
> +        .andExpect(status().isOk());
Integration test에서는 가능한 많은 것을 확인해주는것이 좋습니다. 모든 레이어를 테스트해야하니까요. put의 status가 ok인지 확인한 뒤에, get request로 1번 notice를 받아와서 제대로 값이 들어갔는지 확인하면 좋겠네요. 

noticeRequestDto도 제가 NoticeRequestDtoTest.java 에서 올려드린 `getNoticeRequestDto(String title, String content)`를 사용해서 `NoticeRequestDto noticeRequestDto = getNoticeRequestDtoFixture("updated title", "updated content");` 정도로 생성하면 실제로 새로운 값이 데이터베이스에 잘 들어가는지 확인할 수 있을 것 같습니다.

아참 그리고 put request의 응답은 비어있으니 `.andExpect(jsonPath("$").doesNotExist());`를 추가하면 더 좋겠습니다

2019-08-01 16:18 UTC, me0768 commented on mother-api/src/integrationTest/java/community/mother/notice/api/NoticeControllerIntTest.java
> +        .andExpect(status().isOk());
많은걸 할수 있네요..! 반영했습니다

2019-08-01 16:20 UTC, me0768 commented on mother-api/src/test/java/community/mother/notice/api/dto/NoticeRequestDtoTest.java
> +
오버로딩을 생각못했네요
그리고 저 Utils 정말 유용한거같아요 👍

2019-08-01 16:21 UTC, me0768 commented
늦은밤까지 감사합니다 bb

2019-08-02 09:41 UTC, myeongjae-kim commented on mother-api/src/integrationTest/java/community/mother/notice/api/NoticeControllerIntTest.java
> +    // TODO: 2019-08-02 check if it is actually updated when get method is implemented.
헉ㅋㅋ get이 없었네요...

2019-08-02 10:05 UTC, myeongjae-kim requested changes

2019-08-02 10:05 UTC, myeongjae-kim commented on mother-api/src/main/java/community/mother/notice/service/NoticeService.java
> +    noticeRepository.save(savedNotice);
save(savedNotice)보다는 save(noticeToUpdate)가 나을 것 같아서, savedNotice대신 noticeToUpdate로 변수명을 지으면 어떨까요~~

2019-08-02 10:10 UTC, me0768 commented on mother-api/src/main/java/community/mother/notice/service/NoticeService.java
> +    noticeRepository.save(savedNotice);
좋습니다~~

2019-08-02 10:27 UTC, myeongjae-kim approved these changes

2019-08-02 10:29 UTC, jjj0611 approved these changes

2019-08-02 10:30 UTC, merged