31 content post
kiworkshop/community pull request #32
Opened 2019-08-20 02:32 UTC by simplelife5757

##### Checklist

- [ ] test coverage is above 95%
- [ ] no warnings from `checkstyle`

### Description of change

- 
- 
-

2019-08-26 12:27 UTC, hrzon approved these changes

2019-08-26 12:27 UTC, hrzon commented on content-api/src/main/java/community/content/simplelife/post/domain/Post.java
> +  private LocalDateTime createdAt;
저희는 언젠가 글로벌 서비스도 할거기 때문에(ㅋㅋㅋ) ZonedDateTime을 사용하시는게 더 좋을것같습니다.

농담이구, 프론트엔드에서 시간 표시할 때 타임존이 없으면 애매한 경우가 생겨서요. 컴퓨터 시간대가 다르면 시간이 바뀌어버린다든지 그렇습니다.

2019-08-26 12:27 UTC, hrzon commented on content-api/src/main/java/community/content/simplelife/post/domain/Post.java
> +  private String storedFileName;
originalFileName과 storedFileName은 어떤 역할을 하나요?

2019-08-26 12:27 UTC, hrzon commented on content-api/src/test/java/community/content/simplelife/tag/domain/TagTest.java
> +    return Tag.builder().tag("tag").build();
👏👏

2019-08-26 12:27 UTC, hrzon commented on content-api/src/test/java/community/content/simplelife/post/domain/PostTest.java
> +public class PostTest {
getPostFixture도 만들어두시면 나중에 크게 쓸모가 있으실거에요

2019-08-26 12:28 UTC, hrzon requested changes
앗 잘못눌렀습니다.. 그리구 또 회사계정으로 리뷰해버렸네요;;

2019-08-26 13:08 UTC, simplelife5757 commented on content-api/src/main/java/community/content/simplelife/post/domain/Post.java
> +  private String storedFileName;
사실 이 부분이 좀 헷갈리는 것 같아요. 한 포스트에 여러 사진을 저장하고 싶을 때 여러 사진들을 identify할 수 있는 이름이 하나 필요하다고 생각 했고 계획은 List<String> originalFileName 으로 하려 했으나 jpa에서 콜렉션으로 저장하는게 쉽지 않은 것 같아 FileName 도메인을 새로 만들어야 하나 고민하고 있었습니다. 윽 어떻게 설계하는 것이 좋을까요??

2019-08-26 13:09 UTC, simplelife5757 commented on content-api/src/main/java/community/content/simplelife/post/domain/Post.java
> +  private LocalDateTime createdAt;
그렇군요! 감사합니다ㅎㅎ

2019-08-26 22:21 UTC, myangw submitted a review, later dismissed

2019-08-30 07:00 UTC, myeongjae-kim commented on content-api/src/main/java/community/content/simplelife/post/domain/Post.java
> +  private String storedFileName;
일단, 포스트 내용에 여러개의 사진을 넣는것이라면 `content`에 img 태그가 들어갈테니 따로 필드를 만들지 않아도 될 것 같아요.

내용이 아니라 다른 목적으로 쓴다면 필드명을 좀 더 구체적으로 지으면 좋을 것 같습니다. 그리고 저희는 데이터베이스 자체에 이미지를 저장하지 않고, 이미지는 S3에 저장한 뒤 데이터베이스에는 URL만 저장할거에요. 따라서 `originalFileName` 대신 `originalImageUrl`이 더 나을 것 같습니다.

여러개의 문자열을 저장하고 싶은 경우라면 ElementalCollection을 활용하면 편합니다.

<https://www.callicoder.com/hibernate-spring-boot-jpa-element-collection-demo/>의 예시는

```java
    @ElementCollection
    @CollectionTable(name = "user_phone_numbers", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "phone_number")
    private Set<String> phoneNumbers = new HashSet<>();
```

위 예제는 `user_phone_numbers` 테이블을 만들어서 `user`테이블과 join하네욥. `user_phone_numbers`의 컬럼은 `user_id`와 `phone_number` 입니다.

값이 중복되도 상관없다면 Set대신 List를 쓰면 됩니다.

2019-09-03 04:02 UTC, simplelife5757 commented on content-api/src/main/java/community/content/simplelife/post/domain/Post.java
> +  private String storedFileName;
감사합니다 선생님 ㅎㅎ

2019-09-08 11:22 UTC, myeongjae-kim submitted a review, later dismissed

2019-09-12 02:47 UTC, myangw submitted a review, later dismissed

2019-09-17 09:00 UTC, jjj0611 submitted a review, later dismissed

2019-10-03 04:28 UTC, myeongjae-kim approved these changes

2019-10-10 10:49 UTC, jjj0611 approved these changes

2019-10-10 10:49 UTC, merged